name: Aaron Grant Theatrical
favicon: null
layout_spectrum: 0.67492
typography_spectrum: 0.79705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ecd9'
    - '#886c56'
    - '#a58b69'
    - '#7b2d1c'
    - '#b14931'
  brandStrength: 0.8125
  lightness: 0.03142028604634106
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
