name: Aaron Grant Theatrical
favicon: null
layout_spectrum: 0.35825125966221094
typography_spectrum: 0.38404791080392897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5386195397004485
  lightness: 0.03142028604634106
  saturation: 0.2484992330428213
  rhythmicContrast: 0.6552021794486791
purpose: []
